{% set name = "jupyterlab-tour" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 78b423e3c262dd5d812c83c840f09a35f28d54319bae10a8d42bf7a86bfc6aa0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --install-option="--skip-npm" -vv

requirements:
  host:
    - python >=3.6
    - pip
    - jupyterlab >=3.0.0
    - jupyter-packaging >=0.7.9,<0.8.0
  run:
    - python >=3.6
    - jupyterlab >=3.0.0

test:
  commands:
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-tour.*OK.*(python, jupyterlab-tour)"

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-tour
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab UI tour built on jupyterlab-tutorial and react-joyride.

extra:
  recipe-maintainers:
    - bollwyvl
    - fcollonval
