{% set name = "jupyterlab-tour" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bbc06a11ab1f9a9958c49d13df38bcd0f0c92f5dc9168218430313932b2cf2c3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-jupyter-builder >=0.5
    - hatch-nodejs-version
    - hatchling >=1.5.0
    - jupyterlab =4
    - pip
    - python >=3.8,<4.0
  run:
    - python >=3.8,<4.0

test:
  requires:
    - pip
    - jupyterlab
  commands:
    - pip check
    - jupyter labextension list 2>&1 | grep -ie "jupyterlab-tour.*OK.*(python, jupyterlab-tour)"

about:
  home: https://github.com/jupyterlab-contrib/jupyterlab-tour
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A JupyterLab UI tour built on jupyterlab-tutorial and react-joyride.

extra:
  recipe-maintainers:
    - bollwyvl
    - fcollonval
